const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
module.exports=function(p,profile){
 const posts=p.gallery.filter(i=>!i.group.includes('Carousel'));
 const sets=[...new Set(p.gallery.filter(i=>i.group.includes('Carousel')).map(i=>i.group))].map(group=>({title:group.replace(' Carousel',''),slides:p.gallery.filter(i=>i.group===group).flatMap(i=>Array.from({length:i.panels||1},(_,index)=>({...i,panel:index,panels:i.panels||1})))}));
 const tabs=active=>`<nav class="social-tabs" aria-label="Social media sections"><a href="work-social-media-designs.html" ${active==='posts'?'aria-current="page"':''}>Posts <span>${posts.length}</span></a><a href="social-carousels.html" ${active==='carousels'?'aria-current="page"':''}>Carousels <span>${sets.length}</span></a></nav>`;
 const dialog=`<dialog id="page-view"><button type="button" class="close" aria-label="Close enlarged design">×</button><img alt=""><p></p></dialog>`;
 const postsBody=`<div class="social-feed">${profile}${tabs('posts')}<h2 class="social-section-title">Social posts</h2><p class="social-grid-count">${posts.length} designs</p><div class="social-post-grid">${posts.map(i=>`<button class="social-post page-expand" type="button" aria-label="Enlarge ${esc(i.alt)}"><img src="${i.src}" alt="${esc(i.alt)}" loading="lazy" decoding="async"><span class="post-collection">${esc(i.group)}</span></button>`).join('')}</div></div>${dialog}`;
 const carouselBody=`<div class="social-feed">${profile}${tabs('carousels')}<h2 class="social-section-title">Carousel collections</h2><p class="lead carousel-lead">Open a collection to browse its slides.</p><div class="carousel-grid">${sets.map(set=>{const i=set.slides[0];return `<button class="carousel-card glass" type="button" data-carousel="${esc(JSON.stringify(set))}" aria-label="Open ${esc(set.title)} carousel"><span class="carousel-thumb"><img src="${i.src}" alt="${esc(set.title)}" loading="lazy" style="width:${i.panels*100}%;max-width:none"><span class="slide-badge">▣ ${set.slides.length} slides</span></span><span class="carousel-title">${esc(set.title)} <span>↗</span></span></button>`;}).join('')}</div></div><dialog id="carousel-view"><button class="close" type="button" aria-label="Close carousel">×</button><h2></h2><div class="carousel-window"><img alt=""></div><div class="carousel-controls"><button type="button" data-slide-prev aria-label="Previous slide">←</button><span aria-live="polite"></span><button type="button" data-slide-next aria-label="Next slide">→</button></div><a class="carousel-original" href="#" target="_blank" rel="noopener">View full artwork ↗</a></dialog>`;
 return {posts:postsBody,carousels:carouselBody};
};
